name: Build Aseprite for Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build-aseprite-windows:
    name: Build Aseprite (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout Aseprite source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Skia for Windows (prebuilt)
        run: |
          Invoke-WebRequest -Uri "https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip" -OutFile "skia.zip"
          Expand-Archive -Path "skia.zip" -DestinationPath "skia"
        shell: powershell

      - name: Setup MSVC build tools
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Ninja
        uses: aseprite/get-ninja@main

      - name: Configure with CMake
        run: |
          cmake -S . -B build -G Ninja ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DLAF_BACKEND=skia ^
            -DSKIA_DIR=${{ github.workspace }}\skia ^
            -DSKIA_LIBRARY_DIR=${{ github.workspace }}\skia\out\Release-x64 ^
            -DSKIA_LIBRARY=${{ github.workspace }}\skia\out\Release-x64\skia.lib ^
            -DENABLE_TESTS=OFF ^
            -DENABLE_CCACHE=OFF ^
            -DENABLE_UPDATER=OFF
        shell: cmd

      - name: Build Aseprite
        run: ninja -C build
        shell: cmd

      - name: Enable portable mode
        working-directory: build\bin
        run: echo. > aseprite.ini
        shell: cmd

      - name: Package as ZIP
        working-directory: build\bin
        run: 7z a Aseprite-Windows-Release.zip *
        shell: cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: aseprite-windows-release
          path: build/bin/Aseprite-Windows-Release.zip
